version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
platform: Any CPU
configuration: Debug
before_build:
  - cmd: nuget restore RoslynMonoFamix.sln -verbosity detailed
build:
  parallel: true                  # enable MSBuild parallel builds
  project: RoslynMonoFamix.sln    # path to Visual Studio solution or projec
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifact
  # MSBuild verbosity level
  verbosity: normal
after_build:
  - cmd: RoslynMonoFamix\bin\Debug\RoslynMonoFamix.exe SampleCode\SampleCode.sln Output.mse
  - cmd:  type Output.mse